import { Box } from "@chakra-ui/react";
import { NextPage } from "next";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useRecoilState } from "recoil";

import { OrganismNavbar } from "components/organisms";

import { authStore } from "store";
import { useAuth } from "hooks";
import Head from "next/head";

interface AuthorizedLayoutProps {
  children: React.ReactNode;
  title?: string;
}

const AuthorizedLayout: NextPage<AuthorizedLayoutProps> = ({
  children,
  title,
}): any => {
  const [auth, setAuth] = useRecoilState(authStore.authAtom);
  const { data, isSuccess } = useAuth.useGetProfile();

  useEffect(() => {
    if (data || isSuccess) {
      initialFetchAuth();
    }
  }, [data, isSuccess]);

  const router = useRouter();

  useEffect(() => {
    if (!auth.isAuthenticated && router.isReady) router.replace("/login");
  }, [auth.isAuthenticated, router]);

  const initialFetchAuth = () => {
    const transformFollowingToArray = data?.data?.user?.following?.map(
      (val: any) => val.followerId
    );

    setAuth((prevState) => {
      return {
        ...prevState,
        user: {
          ...data?.data?.user,
        },
        followingState: transformFollowingToArray,
      };
    });
  };

  return (
    <Box>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <OrganismNavbar />
      {children}
    </Box>
  );
};

export default AuthorizedLayout;
