import Head from "next/head";
import React from "react";

const LoginLayout: React.FC = ({ children }) => {
  return (
    <>
      <Head>
        <title>Login to Apps!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};

export default LoginLayout;
