import { AuthorizedLayout } from "layouts";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRecoilValue } from "recoil";
import { authStore } from "store";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const auth = useRecoilValue(authStore.authAtom);

  return (
    <AuthorizedLayout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </AuthorizedLayout>
  );
};

export default Home;
